# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fedora 中文用户组
email: chinese@lists.fedoraproject.org
tagline: Fedora Zhongwen (Chinese) User Group, FZUG, Fedora 中文社区
description: > # this means to ignore newlines until "baseurl:"
  Fedora 中文用户组（Fedora Zhongwen (Chinese) User Group，简称 FZUG），是 Fedora
  中文用户组成的社区。FZUG 由众多已创办 Fedora 中文社区多年的 Fedora 爱好者共同创建于 2008 年。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zh.fedoracommunity.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: FZUG
  card: summary
logo: /assets/FZUG-logo.png
social:
  name: FZUG
  links:
    - https://www.twitter.com/FZUG
    - https://github.com/FZUG
    - https://www.facebook.com/groups/fedora.chinesegroup
    - https://t.me/fedorazh
locale: zh_CN
# twitter_username and github_username are used in social.html in minima theme in footer.
twitter_username: FZUG
github_username: FZUG

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
